version: 0.2

env:
  variables:
    # Set your repo URI here or in project env vars
    REPOSITORY_URI: 051502724052.dkr.ecr.ap-south-1.amazonaws.com/bosspro/frontend

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase - node $(node -v) npm $(npm -v)"

  pre_build:
    commands:
      - echo "Entered pre_build phase..."
      - echo "Installing Node.js dependencies..."
      - npm ci || npm install
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "COMMIT_HASH=$COMMIT_HASH IMAGE_TAG=$IMAGE_TAG"
      - |
        # Soft warning if Clerk publishable key is missing — do NOT fail the build
        if [ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
          echo "WARNING: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is not set. Proceeding without it."
        else
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY found in environment."
        fi

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Building the Next.js app..."
      - npm run build
      - echo "Docker build..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo "Post build started on $(date)"
      - |
        # If the image exists, push & write imagedefinitions.json pointing to the image
        if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "^${REPOSITORY_URI}:latest$"; then
          echo "Pushing Docker images..."
          docker push $REPOSITORY_URI:latest
          docker push $REPOSITORY_URI:$IMAGE_TAG
          DOCKER_CONTAINER_NAME=javatechie-registry
          printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
          echo "imagedefinitions.json:"
          cat imagedefinitions.json
        else
          echo "No Docker image found. Writing placeholder imagedefinitions.json to prevent artifact upload failure."
          printf '[]' > imagedefinitions.json
          cat imagedefinitions.json
        fi

artifacts:
  files:
    - imagedefinitions.json
