version: 0.2

env:
  variables:
    # public build vars
    REPOSITORY_URI: 051502724052.dkr.ecr.ap-south-1.amazonaws.com/bosspro/frontend
    NEXT_PUBLIC_API_BASE_URL: "https://project.serperp.com"
    NEXT_PUBLIC_GOOGLE_API_BASE_URL: "http://fileservice.serperp.com"
    NEXT_PUBLIC_USER_SERVICE_URL: "https://userservice.serperp.com"
    NEXT_PUBLIC_AI_SERVICE_URL: "https://n8n.serperp.com/webhook/chat"
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: "/sign-in"
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: "/sign-up"

  secrets-manager:
    # CodeBuild will inject this securely at build time (masked in logs)
    # Replace with your secret ARN in Secrets Manager
    CLERK_SECRET_KEY: "arn:aws:secretsmanager:ap-south-1:051502724052:secret:PUBLIC_CLERK-MbmdaJ"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Node $(node -v), npm $(npm -v)"

  pre_build:
    commands:
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo "COMMIT_HASH=$COMMIT_HASH IMAGE_TAG=$IMAGE_TAG"

  build:
    commands:
      - echo "Building app (npm build)..."
      - npm ci
      - npm run build
      - echo "Building docker image..."
      # set variables
      - REPO="$REPOSITORY_URI"
      - TAG="$REPO:latest"
      - IMAGE_TAG="$REPO:$IMAGE_TAG"
      # build with conditional inclusion of publishable key
      - |
        if [ -n "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
          echo "Using NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY build-arg"
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE_URL="$NEXT_PUBLIC_API_BASE_URL" \
            --build-arg NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" \
            -t "$TAG" .
        else
          echo "No NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY provided — building without that arg"
          docker build \
            --build-arg NEXT_PUBLIC_API_BASE_URL="$NEXT_PUBLIC_API_BASE_URL" \
            -t "$TAG" .
        fi

  post_build:
    commands:
      - echo "Tagging image with build tag and pushing to ECR..."
      - docker tag "$REPO:latest" "$REPO:$IMAGE_TAG"
      - docker push "$REPO:latest"
      - docker push "$REPO:$IMAGE_TAG"
      - echo "Writing imagedefinitions.json"
      - printf '[{"name":"%s","imageUri":"%s"}]' "frontend" "$REPO:$IMAGE_TAG" > imagedefinitions.json
      - cat imagedefinitions.json
