version: 0.2

env:
  variables:
    # Replace this with your repo URI or set via CodeBuild project env vars
    REPOSITORY_URI: 051502724052.dkr.ecr.ap-south-1.amazonaws.com/bosspro/frontend

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Install phase - node $(node -v) npm $(npm -v)"

  pre_build:
    commands:
      - echo "Entered pre_build phase..."
      - echo "Installing Node.js dependencies..."
      - npm ci || npm install
      - echo "Logging in to Amazon ECR..."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7 || echo "local")
      - export IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}' || date +%s)
      - echo "COMMIT_HASH=$COMMIT_HASH IMAGE_TAG=$IMAGE_TAG"
      - |
        if [ -z "$NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY" ]; then
          echo "WARNING: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY is not set. Proceeding without it."
        else
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY found in environment."
        fi

build:
  commands:
    - echo "Build started on $(date)"
    - echo "Running Next.js build..."
    - |
      if npm run build; then
        echo "Next build succeeded — building Docker image..."
        docker build -t $REPOSITORY_URI:latest .
        docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      else
        echo "Next build failed — skipping Docker build."
        # optional: exit 1 to fail the whole build instead of skipping
        # exit 1
      fi

  post_build:
    commands:
      - echo "Post build started on $(date)"
      - |
        if docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "^${REPOSITORY_URI}:latest$"; then
          echo "Pushing Docker images to ECR..."
          docker push $REPOSITORY_URI:latest
          docker push $REPOSITORY_URI:$IMAGE_TAG
          DOCKER_CONTAINER_NAME=javatechie-registry
          printf '[{"name":"%s","imageUri":"%s"}]' "$DOCKER_CONTAINER_NAME" "$REPOSITORY_URI:$IMAGE_TAG" > imagedefinitions.json
          echo "imagedefinitions.json:"
          cat imagedefinitions.json
        else
          echo "No Docker image built. Creating placeholder imagedefinitions.json."
          printf '[]' > imagedefinitions.json
          cat imagedefinitions.json
        fi

artifacts:
  files:
    - imagedefinitions.json
